### ISSUE TITLE
terraform prompts for dnsimple API info

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/OpenStackWorksOnArm#9]
Terraform prompts for information about a "dnsimple" account, but the README doesn't describe what this detail does or how to configure it.

I think it's related to managing domains at https://dnsimple.com/

I continued on giving null answers to the prompts, and Terraform started to deploy, we'll see what happens!

**Comment by vielmetti** [comment]
Error log when I put in nulls for dnsimple prompts:

```
* dnsimple_record.controller-dns: 1 error(s) occurred:

* dnsimple_record.controller-dns: Failed to create DNSimple Record: POST https://api.dnsimple.com/v2/zones/openstacksandiego.us/records: 404 Not Found
* dnsimple_record.dashboard-dns: 1 error(s) occurred:

* dnsimple_record.dashboard-dns: Failed to create DNSimple Record: POST https://api.dnsimple.com/v2/zones/openstacksandiego.us/records: 404 Not Found
```

**Comment by johnstudarus** [comment]
If you _really_ want to use DNS, you'll need an account at DNSimple and a domain.

You'll have to follow the instructions in DNS.tf including setting these environment variables.
export DNSIMPLE_ACCOUNT=
export DNSIMPLE_TOKEN=

However, since this really isn't needed for normal use, I'm going to turn off this feature.
